### ISSUE TITLE
你好，请问为什么我的actions打开之后，没有run workflow的选项？

### ISSUE THREAD

**Issue by linjie5492** [xiaohuanxiong0985/autocheckin#1]
你好，请问为什么我的actions打开之后，没有run workflow的选项？

**Comment by xiaohuanxiong0985** [comment]
没有的话点击new workflow创建对应的流就行

**Comment by xiaohuanxiongi** [comment]
第一次使用是有个绿色的按钮,表示你晓得怎么使用流,点击就行了,然后第二天就可以自动签到了

**Comment by linjie5492** [comment]
嗯，昨天开了，今天跑过了，不过我好像失败了
![image](https://user-images.githubusercontent.com/39755834/153987681-f96f5107-9068-43e0-bdf1-6a6bc217ceed.png)

**Comment by xiaohuanxiongi** [comment]
应该是早上人多,我下午重新跑了一下可以,修改一下运行时间就行了.国际时间0点跑不得行,会出现你上面那个问题

**Comment by xiaohuanxiong0985** [comment]
应该是早上人多,我下午重新跑了一下可以,修改一下运行时间就行了.国际时间0点跑不得行,会出现你上面那个问题
