### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by Minori-ty** [xiaohuanxiong0985/autocheckin#2]
![image](https://user-images.githubusercontent.com/79521943/183328758-446f6401-772c-4f20-b231-173c4337097c.png)

**Comment by xiaohuanxiongi** [comment]
稍等,找到问题了,修复一下

**Comment by xiaohuanxiongi** [comment]
已解决

**Comment by Minori-ty** [comment]
![image](https://user-images.githubusercontent.com/79521943/183388396-ce127ecd-eedb-4214-8b33-cf4ba5af5948.png)
签到失败是什么问题。我是在贴吧页面随便找个请求复制cookie的

**Comment by Minori-ty** [comment]
一直显示我没有实名认证，但是我已经是实名认证了的

**Comment by xiaohuanxiongi** [comment]
这个是已经签到过了.

**Comment by xiaohuanxiongi** [comment]
> 一直显示我没有实名认证，但我已经是实名认证了

你前面截图那个意思是签到过了,error的信息就是已签到,不能重复签到了,然后下面那个是你没有设置设置邮件授权码,所以签到失败了没有给你发邮件的意思
